"""cascade delete

Revision ID: bf4a93914a8e
Revises: 9f263884aca5
Create Date: 2024-12-06 10:52:00.123578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a93914a8e'
down_revision: Union[str, None] = '9f263884aca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name='properties', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_properties_product_id', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name='properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_product_id', 'properties', type_='foreignkey')
    # ### end Alembic commands ###
