"""updated1

Revision ID: 67dae2976346
Revises: 
Create Date: 2024-12-05 16:08:12.505365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mssql.information_schema import columns

# revision identifiers, used by Alembic.
revision: str = '67dae2976346'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name='products', schema=None) as batch_op:
        batch_op.create_unique_constraint(constraint_name='uq_product_model', columns=['model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name='products', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name='uq_product_model', type_='unique')
    # ### end Alembic commands ###
